# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    disable_csrf_role: ROLE_USER
    zone:
        - { path: ^/api/* }
    routing_loader:
        default_format: json
        prefix_methods: api
    format_listener:
        enabled: true
        rules:
        - { path: '^/api/doc', priorities: ['html'], fallback_format: html, prefer_extension: false }
        - { path: '^/api', priorities: ['json'], fallback_format: json, prefer_extension: true }
        - { path: '^/', priorities: ['html', 'json'], fallback_format: html, prefer_extension: true }
    exception:
        exception_controller: 'fos_rest.exception.controller::showAction'
        # Set exceptions status code, may be useful for custom exceptions
        codes:
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        # Set exceptions messages. Set to true to display messages
        messages:
           # 'Symfony\Component\Security\Core\Exception\AccessDeniedException': false
           # 'Symfony\Component\Routing\Exception\ResourceNotFoundException': true
    service:
        templating: twig
    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    # view:
    #     force_redirects:
    #         html: true
    #         json: false
    #     templating_formats:
    #         html: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
