jms_serializer:
    visitors:
        xml:
            format_output: '%kernel.debug%'
    
    default_context:
        serialization:
            enable_max_depth_checks: true
        deserialization:
            enable_max_depth_checks: false
#    metadata:
#        auto_detection: false
#        directories:
#            any-name:
#                namespace_prefix: "My\\FooBundle"
#                path: "@MyFooBundle/Resources/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
