stages:
  - build
  - test
  - deploy

variables:
  CONTAINER_IMAGE: registry.remotelabz.com/$CI_PROJECT_PATH
  MYSQL_DATABASE: symfony
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_USER: symfony
  MYSQL_PASSWORD: $MYSQL_PASSWORD
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:app:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build -f ./docker/Dockerfile --cache-from $CONTAINER_IMAGE --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:latest
  tags:
    - build

# TODO edit test mode
test:phpunit:
  stage: test
  image: docker:latest
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - cp -rf .env.dist .env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker-compose up -d
    - docker-compose exec -T app /bin/ls -la /app
    - docker-compose exec -T app /bin/cat /app/.env
    - docker-compose exec -T app /app/bin/console make:migration
    - docker-compose exec -T app /app/bin/console doctrine:migrations:migrate -n
    - docker-compose exec -T app /app/bin/console doctrine:fixtures:load -n
    - docker-compose exec -T app /app/bin/console assets:install --symlink public
    - docker-compose exec -T app /app/bin/phpunit --configuration phpunit.xml.dist
  tags:
    - test

# TODO stage with apache to upload on public server
deploy:staging:
  stage: deploy
  script:
    - cp -rf .env.dist .env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
    - docker-compose stop
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker-compose up -d
    - docker-compose exec -T app /app/bin/console make:migration
    - docker-compose exec -T app /app/bin/console doctrine:migrations:migrate -n
    - docker-compose exec -T app /app/bin/console doctrine:fixtures:load -n
    - docker-compose exec -T app /app/bin/console assets:install --symlink public
  environment:
    name: staging
    url: http://10.22.9.136/
  dependencies:
    - test:phpunit
  tags:
    - deploy
