stages:
  - build
  - test
  - deploy

variables:
  MYSQL_DATABASE: symfony
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_USER: symfony
  MYSQL_PASSWORD: $MYSQL_PASSWORD

before_script:
  - docker login -u marcadia -p $DOCKER_PASSWORD

build:app:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    # - docker login -u marcadia -p $DOCKER_PASSWORD
    - docker run --rm --name composer_install -v "$PWD":/var/www/app -w /var/www/app --user $(id -u):$(id -g) composer:latest install --no-suggest --no-progress
    - docker build --pull -t "194.57.105.124:6361/crestic/remotelabzv2:$CI_COMMIT_REF_SLUG" .
    - docker push "194.57.105.124:6361/crestic/remotelabzv2:$CI_COMMIT_REF_SLUG"
  tags:
    - build

test:phpunit:
  stage: test
  image: "194.57.105.124:6361/crestic/remotelabzv2:$CI_COMMIT_REF_SLUG"
  services:
    - mysql:5.7
  before_script:
    # - docker login -u marcadia -p $DOCKER_PASSWORD
    - cd /app
    - echo "DATABASE_URL=mysql://symfony:$MYSQL_PASSWORD@mysql/symfony" >> .env
    - bin/console doctrine:migrations:migrate -n
    - bin/console doctrine:fixtures:load -n
  script:
    - bin/phpunit --configuration phpunit.xml.dist --colors=never
  only:
    - [master]
  tags:
    - test

deploy:staging:
  stage: deploy
  script:
    - docker-compose -f docker-compose.yml pull --parallel
    - docker-compose -f docker-compose.yml up -d
    - docker-compose -f docker-compose.yml exec -T app sh -c 'echo "DATABASE_URL=mysql://symfony:$MYSQL_PASSWORD@mysql/symfony" >> .env'
    - docker-compose -f docker-compose.yml exec -T app bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration
    - docker-compose -f docker-compose.yml exec -T app bin/console doctrine:fixtures:load --no-interaction
    - docker-compose -f docker-compose.yml exec -T -d app bin/console server:start 0.0.0.0:8000
  environment:
    name: staging
    url: http://10.22.9.136/
  dependencies:
    - build:app
    - test:phpunit
  tags:
    - deploy
