stages:
  - build
  - test
  - deploy

variables:
  MYSQL_DATABASE: symfony
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_USER: symfony
  MYSQL_PASSWORD: $MYSQL_PASSWORD

# build:app:
#   stage: build
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker run --rm --name composer_install -v "$PWD":/var/www/app -w /var/www/app --user $(id -u):$(id -g) composer:latest install --no-suggest --no-progress
#     - docker build --pull -t "194.57.105.124:6361/crestic/remotelabzv2:$CI_COMMIT_REF_SLUG" .
#     - docker push "194.57.105.124:6361/crestic/remotelabzv2:$CI_COMMIT_REF_SLUG"
#   tags:
#     - build

test:phpunit:
  stage: test
  image: docker
  services:
    - mysql:5.7
    - docker:dind
  before_script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - cp -rf .env.dist .env
    - "printenv >> .env"
    - docker-compose up --build -d
  script:
    - bin/phpunit --configuration phpunit.xml.dist --colors=never
  only:
    - master
  tags:
    - test

# TODO stage with apache to upload on public server
deploy:staging:
  stage: deploy
  before_script:
    - cp -rf .env.dist .env
    - "printenv >> .env"
  script:
    - docker-compose stop
    - docker-compose up --build -d
  environment:
    name: staging
    url: http://10.22.9.136/
  dependencies:
    - test:phpunit
  tags:
    - deploy
