stages:
  - build
  - test
  - deploy

variables:
  REGISTRY_URL: registry.remotelabz.com/$CI_PROJECT_PATH/
  MYSQL_DATABASE: symfony
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_USER: symfony
  MYSQL_PASSWORD: $MYSQL_PASSWORD

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:docker:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2
  script:
    - cp -rf .env.dist .env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
    - apk add --no-cache py-pip
    - pip install docker-compose
    - docker-compose pull --ignore-pull-failures
    - docker-compose build
    - docker-compose push
  tags:
    - build

test:phpunit:
  stage: test
  image: docker:stable
  services: 
    - docker:dind
  script:
    - apk add --no-cache py-pip
    - pip install docker-compose
    - cp -rf .env.dist .env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
    - docker-compose pull
    - docker-compose up -d
    - docker-compose run -T yarn encore dev
    - docker-compose run -T console doctrine:migrations:migrate -n
    - docker-compose run -T console doctrine:fixtures:load -n
    - docker-compose run -T console assets:install --symlink public --relative
    - docker-compose run -T --entrypoint /app/bin/phpunit console --configuration phpunit.xml.dist
  dependencies:
    - build:docker
  tags:
    - test

# TODO stage with apache to upload on public server
deploy:review:
  stage: deploy
  script:
    - cp -rf .env.dist .env
    - echo MYSQL_PASSWORD=$MYSQL_PASSWORD >> .env
    - docker-compose stop
    - docker-compose pull
    - docker-compose up -d
    - docker-compose run -T yarn encore dev
    - docker-compose run -T console doctrine:migrations:migrate -n
    - docker-compose run -T console doctrine:fixtures:load -n
    - docker-compose run -T console assets:install --symlink public --relative
  environment:
    name: review
    url: http://10.22.9.136/
    on_stop: deploy:review:stop
  dependencies:
    - test:phpunit
  tags:
    - deploy

deploy:review:stop:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - docker-compose stop
  when: manual
  environment:
    name: review
    action: stop
  tags:
    - deploy

deploy:staging:
  stage: deploy
  when: manual
  script:
    - echo 1
  environment:
    name: staging
    url: http://www.remotelabz.com/
    # on_stop: deploy:staging:stop
  tags:
    - staging