version: '3'

volumes:
    database-volume:

services:
    app:
        build: .
        image: app:latest
        volumes:
            - .:/app
        ports:
            - "80:8000"
        depends_on:
            - mysql
        tty: true
        entrypoint: docker-php-entrypoint
        command: entrypoint.sh
        restart: on-failure

    mysql:
        image: mysql:5.7
        volumes:
            - database-volume:/var/lib/mysql
        env_file: .env
        restart: on-failure
