version: '2'

volumes:
    database-volume:
    app:

services:
    app:
        image: "194.57.105.124:6361/crestic/remotelabzv2:${CI_COMMIT_REF_SLUG}"
        working_dir: /app
        environment:
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: symfony
            MYSQL_DATABASE: symfony
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            BRANCH: gitlab-ci-setup
            DATABASE_HOST: "mysql"
            DATABASE_PORT: "3306"
            DATABASE_NAME: "symfony"
            DATABASE_USERNAME: "symfony"
            DATABASE_PASSWORD: "${MYSQL_PASSWORD}"
            SECRET_TOKEN: "${SECRET_TOKEN}"
            SYMFONY_ENV: prod
        volumes:
            - app:/app
        ports:
            - "80:8000"
        tty: true
        restart: always

    mysql:
        image: mysql:5.7
        volumes:
            - database-volume:/var/lib/mysql
        environment:
            MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_USER: symfony
            MYSQL_DATABASE: symfony
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: always
