version: '3'

volumes:
    database-volume:

services:
    app:
        image: registry.remotelabz.com/crestic/remotelabzv2:latest
        ports:
            - "80:8000"
        volumes:
            - ./.env:/app/.env
        depends_on:
            - mysql
        tty: true
        restart: on-failure

    mysql:
        image: mysql:5.7
        volumes:
            - database-volume:/var/lib/mysql
        env_file: .env
        restart: on-failure
