version: '3'

volumes:
    database-volume:
    app:



services:
    app:
        build: .
        image: app:latest
        volumes:
            - .:/app
        env_file: .env
        environment:
            # MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            # MYSQL_USER: "${MYSQL_USER}"
            # MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
            - "80:8000"
        depends_on:
            - mysql
        tty: true
        restart: on-failure

    mysql:
        image: mysql:5.7
        volumes:
            - database-volume:/var/lib/mysql
        env_file: .env
        environment:
            # MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
            # MYSQL_USER: "${MYSQL_USER}"
            # MYSQL_DATABASE: "${MYSQL_DATABASE}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        restart: on-failure

    node:
        build: yarn/.
        restart: on-failure
