version: '3.2'

volumes:
    database-volume:

services:
    app:
        build:
            dockerfile: ./docker/dev/Dockerfile
            context: .
            cache_from: 
                - remotelabzv2:barebone
                - php:7.2
        image: remotelabzv2:barebone
        volumes:
            - ./:/app
        # ports:
        #     - "80:8000"
        depends_on:
            - mysql
        tty: true

    mysql:
        image: mysql:5.7
        volumes:
            - database-volume:/var/lib/mysql
        env_file: .env
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: 1

    apache:
        image: registry.remotelabz.com/crestic/remotelabzv2:apache
        volumes:
            - ./:/app
        ports:
            - "80:80"