# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username
        db_provider:
            entity:
                class: AppBundle:UserSAML
                property: username

    encoders:
        UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:       [ROLE_USER, ROLE_ENSEIGNANT, ROLE_ETUDIANT]
        ROLE_ENSEIGNANT:  [ROLE_USER, ROLE_ETUDIANT]
        ROLE_ETUDIANT:    ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            provider: main
            remote_user:
                provider: db_provider
                user: REMOTE_USER
            form_login:
                provider: main
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /auth
                always_use_default_target_path: false
                csrf_token_generator: security.csrf.token_manager
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                secret:        %secret%

    access_control:
        - { path: ^/auth, roles: [ROLE_USER] }
        - { path: ^/admin, roles: [ROLE_SUPERADMIN,ROLE_ADMIN] }
        - { path: ^/control, roles: [ROLE_SUPERADMIN,ROLE_ADMIN,ROLE_ENSEIGNANT,ROLE_ETUDIANT] }
        - { path: ^/ens, roles: [ROLE_SUPERADMIN,ROLE_ADMIN,ROLE_ENSEIGNANT] }
