#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

# home:
#     path: /
#     controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
#     defaults:
#         route: users

shib_login:
    path: /Shibboleth.sso/Login

shib_logout:
    path: /Shibboleth.sso/Logout

gesdinet_jwt_refresh_token:
    path:       /api/auth/refresh
    controller: gesdinet.jwtrefreshtoken::refresh