#index:
#    path: /
#    controller: App\Controller\DefaultController::index

logout:
    path: /logout

api_login_check:
    path: /api/auth

home:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: users

shib_login:
    path: /Shibboleth.sso/Login

shib_logout:
    path: /Shibboleth.sso/Logout